# Production configuration for AI Corporation

# Database
POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
POSTGRES_USER: ai_corp
POSTGRES_DB: ai_corporation

# MinIO
MINIO_ROOT_USER: ${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

# Telegram Bot
TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}

# API Keys
CLAUDE_API_KEY: ${CLAUDE_API_KEY}
OPENAI_API_KEY: ${OPENAI_API_KEY}

# Model Configuration
MAX_VRAM_GB: 24
MODEL_QUANTIZATION: q4_K_M

# Task Queue
MAX_CONCURRENT_TASKS: 5
TASK_TIMEOUT_SECONDS: 7200

# Security
JWT_SECRET_KEY: ${JWT_SECRET_KEY}
JWT_ALGORITHM: HS256
JWT_EXPIRE_MINUTES: 1440

# Rate Limiting
RATE_LIMIT_REQUESTS: 50
RATE_LIMIT_WINDOW: 60

# Logging
LOG_LEVEL: INFO
LOG_FILE: /var/log/ai_corporation.log
